/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.GiangVienDAO;
import Model.GiangVien;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS RG
 */
public class formGiangVien extends javax.swing.JFrame {

    /**
     * Creates new form formGiangVien
     */
    public formGiangVien() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGiangVien = new javax.swing.JTable();
        btnQuayLai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaGV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtHocVi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTongSoGV = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Giảng Viên");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DANH SÁCH GIẢNG VIÊN KHOA CNTT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 23, -1, -1));

        tableGiangVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã GV", "Họ Tên", "Học Vị"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableGiangVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGiangVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableGiangVien);
        if (tableGiangVien.getColumnModel().getColumnCount() > 0) {
            tableGiangVien.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 66, 440, 233));

        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/teacher.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 142, 145));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Mã Giàng Viên:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 328, 89, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Họ Tên:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 362, 54, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Học Vị:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 328, 49, -1));
        getContentPane().add(txtMaGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 326, 145, -1));
        getContentPane().add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 360, 145, -1));
        getContentPane().add(txtHocVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 326, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel6.setText("Tổng Số Giàng Viên:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        txtTongSoGV.setEditable(false);
        getContentPane().add(txtTongSoGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 45, -1));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 400, -1, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 400, -1, -1));

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 400, 84, -1));

        btnTimKiem.setText("Tìm Theo Mã GV");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 400, 120, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/teacherList.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, 140));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void loadData()
    {
        GiangVienDAO gvDAO = new GiangVienDAO();
        ArrayList<GiangVien> dsgv = gvDAO.DanhSachGiangVien();
        
        DefaultTableModel tableGV = (DefaultTableModel) this.tableGiangVien.getModel();
        tableGV.setRowCount(0);
        int stt = 0;
        for(GiangVien gv : dsgv)
        {
            stt++;
            Object[] row = new Object[]{ String.valueOf(stt) ,gv.getIdGiangVien(), gv.getTenGiangVien(), gv.getHocVi()};
            tableGV.addRow(row);
        }
        int sl = tableGiangVien.getRowCount();
        txtTongSoGV.setText(String.valueOf(sl));
    }
    
    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void tableGiangVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGiangVienMouseClicked
        txtMaGV.setText(tableGiangVien.getValueAt(tableGiangVien.getSelectedRow(), 1).toString());
        txtHoTen.setText(tableGiangVien.getValueAt(tableGiangVien.getSelectedRow(), 2).toString());
        txtHocVi.setText(tableGiangVien.getValueAt(tableGiangVien.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tableGiangVienMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if("".equals(txtMaGV.getText()) || "".equals(txtHocVi.getText()) || "".equals(txtHoTen.getText()))
        {
            JOptionPane.showMessageDialog(null, "Yêu cầu nhập đẩy đủ thông tin!", "Thông báo!", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            GiangVienDAO gvDAO = new GiangVienDAO();
            GiangVien gv = new GiangVien();
            gv.setIdGiangVien(txtMaGV.getText());
            gv.setTenGiangVien(txtHoTen.getText());
            gv.setHocVi(txtHocVi.getText());
            
            if(gvDAO.ThemGiangVien(gv)==-1)
            {
                JOptionPane.showMessageDialog(null, "Trùng mã giảng viên!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Thêm thành công giảng viên " + txtHoTen.getText());
            }
            loadData();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       
        int row = tableGiangVien.getRowCount();
        
        if ("".equals(txtMaGV.getText())) 
        {
            JOptionPane.showMessageDialog(null, "Yêu cầu nhập mã giảng viên để xóa!", "Thông báo!", JOptionPane.WARNING_MESSAGE);
        } 
        
        else 
        {
            GiangVienDAO gvDAO = new GiangVienDAO();
            GiangVien gv = new GiangVien();
            gv.setIdGiangVien(txtMaGV.getText());

            if (gvDAO.XoaGiangVien(gv) == -1) 
            {
                JOptionPane.showMessageDialog(null, "Xóa thất bại!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            } 
            else 
            {                
                loadData();
                int temp = tableGiangVien.getRowCount();
                if(row>temp)                    
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                else
                    JOptionPane.showMessageDialog(null, "Nhập sai mã!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            }
        }        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtHoTen.setText("");
        txtHocVi.setText("");
        txtMaGV.setText("");
        loadData();

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if("".equals(txtMaGV.getText()) || "".equals(txtHoTen.getText()) || "".equals(txtHocVi.getText()))
        {
            JOptionPane.showMessageDialog(null, "Yêu cầu nhập đầy đủ thông tin!", "Thông báo!", JOptionPane.WARNING_MESSAGE);
        }
        
        else
        {
            GiangVienDAO gvDAO = new GiangVienDAO();
            GiangVien gv = new GiangVien();
            gv.setIdGiangVien(txtMaGV.getText());
            gv.setTenGiangVien(txtHoTen.getText());
            gv.setHocVi(txtHocVi.getText());
            if(gvDAO.CapNhatGiangVien(gv) == -1) 
            {
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            } 
            else 
            {                                 
                 JOptionPane.showMessageDialog(null, "Cập nhật thành công giảng viên " + txtHoTen.getText());
            }
        }

        loadData();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if("".equals(txtMaGV.getText()))
        {
            JOptionPane.showMessageDialog(null, "Yêu cầu nhập mã giảng viên!", "Thông báo!", JOptionPane.WARNING_MESSAGE);
        }
        else
        {            
            GiangVienDAO gvDAO = new GiangVienDAO();
            ArrayList<GiangVien> dsgv = gvDAO.TimKiemGiangVien(txtMaGV.getText());
            DefaultTableModel tableGV = (DefaultTableModel) this.tableGiangVien.getModel();
            tableGV.setRowCount(0);
            int stt = 0;
            for(GiangVien gv : dsgv)
            {
                stt++;
                Object[] row = new Object[]{String.valueOf(stt), gv.getIdGiangVien(), gv.getTenGiangVien(), gv.getHocVi()};
                tableGV.addRow(row);
            }                      
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formGiangVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableGiangVien;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHocVi;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtTongSoGV;
    // End of variables declaration//GEN-END:variables
}
